version: 2
jobs:
  build:
    working_directory: ~/tmp
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:7
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
                - checkout
                - run: npm install
                - run: npm test
                