version: 2
    jobs:
        build:
            docker:     
                - image: circleci/node:7
                working_directory:~/tmp
            steps:
                - checkout
                - run: npm install
                - run: npm test
                